# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "ap-southeast-2"
  # Only these AWS Account IDs may be operated on by this template
  allowed_account_ids = ["575625010278"]
}
